# -*- coding: utf-8 -*-
"""Factorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJSiCzBbNTKyaWoN5aCQp1z9WZrWN4Uj
"""

def factorial(n):
    fact = 1
    for i in range(1, n + 1):
        fact *= i
    return fact

print(factorial(5))